apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerting-relay
  labels:
    app: alerting-relay
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alerting-relay
  template:
    metadata:
      labels:
        app: alerting-relay
    spec:
      containers:
        - name: alerting-relay
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
            - configMapRef:
                name: {{ .Values.configMapName }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
