apiVersion: v2
name: alerting-relay
description: Aggregates Alertmanager alerts into threaded, resolve-updating Slack messages
type: application
version: 0.7.1
appVersion: 0.7.1
home: https://github.com/next-gen-infrastructure/alerting-relay
sources:
  - https://github.com/next-gen-infrastructure/alerting-relay
maintainers:
  - name: next-gen-infrastructure
