name: release-please

on:
  push:
    branches: [main]

env:
  APP_ID: 2625515 # nextgen-release-please

jobs:
  release-please:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_PRIVATE_KEY }}
      - id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
